name: 'My Composite Action'
description: 'Combines multiple steps'
runs:
  using: "composite"
  steps:
    - name: 整理上传固件的名称
      shell: bash
      run: |
        cd $HOME_PATH
        if [[ -n "${{ env.TARGET_PROFILE_IMG }}" ]]; then
           echo "SHANGCHUAN_MINGCHEN=${{ env.SOURCE }}-${{ env.LUCI_EDITION }}-${{ env.TARGET_PROFILE_IMG }}" >> ${GITHUB_ENV}
           echo "RR_RELEASE=b" >> ${GITHUB_ENV}
        else
           echo "SHANGCHUAN_MINGCHEN=${{ env.SOURCE }}-${{ env.LUCI_EDITION }}-${{ env.TARGET_PROFILE }}" >> ${GITHUB_ENV}
           echo "RR_RELEASE=a" >> ${GITHUB_ENV}
        fi
        [[ -z "${DATE}" ]] && echo "DATE=$(date "+%Y%m%d%H%M%S")" >> ${GITHUB_ENV}
        [[ -z "${TONGZHI_DATE}" ]] && echo "TONGZHI_DATE=$(date +%Y年%m月%d日)" >> ${GITHUB_ENV}
        [[ -z "${FIRMWARE_DATE}" ]] && echo "FIRMWARE_DATE=$(date +%Y-%m%d-%H%M)" >> ${GITHUB_ENV}
        echo "TZ_Message=$(date +%Y年%m月%d号%H时%M分)" >> ${GITHUB_ENV}
  
    - name: 上传固件在 github Artifacts
      id: shang
      if: env.UPLOAD_FIRMWARE == 'true'
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.SHANGCHUAN_MINGCHEN }}-firmware-${{ env.FIRMWARE_DATE }}
        path: ${{ env.FIRMWARE_PATH }}
    - name: 上传信息
      if: steps.shang.outcome == 'success' && env.UPLOAD_FIRMWARE == 'true'
      shell: bash
      run: |
        cd $HOME_PATH
        echo "SHANG_MESSAGE=、上传Artifacts" >> ${GITHUB_ENV}
    
    - name: 发布固件
      id: fabu
      if: env.UPLOAD_RELEASE == 'true' && env.RR_RELEASE == 'a'
      uses: ncipollo/release-action@v1.21.0
      with:
        name: ${{ env.SHANGCHUAN_MINGCHEN }}
        tag: a${{ env.DATE }}
        token: ${{ env.REPO_TOKEN }}
        allowUpdates: true
        body: ${{ env.TONGZHI_DATE }}
        artifacts: "${{ env.FIRMWARE_PATH }}/*"
    - name: 发布固件到 Github Releases
      id: nfabu
      if: env.UPLOAD_RELEASE == 'true' && env.RR_RELEASE == 'b'
      uses: ncipollo/release-action@v1.21.0
      with:
        name: ${{ env.amlogic_model }}
        tag: a${{ env.DATE }}
        token: ${{ env.REPO_TOKEN }}
        allowUpdates: true
        artifacts: "${{ env.FIRMWARE_PATH }}/*"
        body: |
          发布日期：${{ env.FIRMWARE_DATE }}
          固件源码：${{ env.SOURCE }}
          内核仓库：${{ env.kernel_usage }}
          写入EMMC：Login to OpenWrt → System → Amlogic Service → Install OpenWrt
    - name: 发布信息
      if: steps.fabu.outcome == 'success' && env.UPLOAD_RELEASE == 'true' || steps.nfabu.outcome == 'success' && env.UPLOAD_RELEASE == 'true'
      shell: bash
      run: |
        cd $HOME_PATH
        echo "FABU_MESSAGE=、发布" >> ${GITHUB_ENV}
        
    - name: Telegram或pushplus信息通知
      if: env.PUSH_PLUS_TOKEN && env.INFORMATION_NOTICE == 'PUSH' || env.TELEGRAM_BOT_TOKEN && env.INFORMATION_NOTICE == 'TG'
      uses: ./.github/actions/notice
      with:
        tg_text: "${{env.SOURCE}}-${{env.LUCI_EDITION}}，${{env.TARGET_PROFILE}}固件，编译${{env.DABAO_MESSAGE}}${{env.SHANG_MESSAGE}}${{env.FABU_MESSAGE}}${{env.YUNDUAN_MESSAGE}}成功，✌️💐(${{env.WAREHOUSE_MAN}}-#${{env.RUN_NUMBER}})，${{env.TZ_Message}}💯"
        push_title: "${{env.SOURCE}}-${{env.LUCI_EDITION}}"
        push_content: "${{env.TARGET_PROFILE}}固件，编译${{env.DABAO_MESSAGE}}${{env.SHANG_MESSAGE}}${{env.FABU_MESSAGE}}${{env.YUNDUAN_MESSAGE}}成功，✌️💐(${{env.WAREHOUSE_MAN}}-#${{env.RUN_NUMBER}})，${{env.TZ_Message}}💯"
branding:
  icon: "terminal"
  color: "gray-dark"
